export const ZOD_MESSAGE_TO_CODE = {
  "Instrument name is required": "instrumentRequired",
  "Instrument name must be 100 characters or less": "instrumentMaxLength",
  "ISIN must be exactly 12 characters": "isinLength",
  "ISIN must be 12 alphanumeric characters (e.g., RO1234567890)": "isinFormat",
  "Issuer name is required": "issuerRequired",
  "Issuer name must be 200 characters or less": "issuerMaxLength",
  "Date is required": "dateRequired",
  "Date must be in YYYY-MM-DD format": "dateFormat",
  "Quantity must be 0 or greater": "quantityMin",
  "Quantity cannot exceed 1 billion units": "quantityMax",
  "Locked amount must be 0 or greater": "lockedMin",
  "Locked amount cannot exceed 1 billion units": "lockedMax",
  "Average price must be at least 0.001 RON": "averagePriceMin",
  "Average price cannot exceed 1,000,000 RON": "averagePriceMax",
  "Reference price must be at least 0.001 RON": "referencePriceMin",
  "Reference price cannot exceed 1,000,000 RON": "referencePriceMax",
  "Locked amount cannot exceed quantity": "lockedExceedsQuantity",
  "Amount must be 0 or greater": "amountMin",
  "Amount cannot exceed 100,000,000 RON": "amountMax",
  "Notes must be 500 characters or less": "notesMaxLength",
  "Bank name is required": "bankRequired",
  "Bank name must be 100 characters or less": "bankMaxLength",
  "Deposit name is required": "depositNameRequired",
  "Deposit name must be 200 characters or less": "depositNameMaxLength",
  "Term must be a whole number of months": "termInt",
  "Term must be at least 1 month": "termMin",
  "Term cannot exceed 120 months": "termMax",
  "Principal must be at least 0.01 RON": "principalMin",
  "Principal cannot exceed 10,000,000 RON": "principalMax",
  "Interest rate must be 0 or greater": "interestRateMin",
  "Interest rate cannot exceed 100%": "interestRateMax",
  "Start date is required": "startDateRequired",
  "Start date must be in YYYY-MM-DD format": "startDateFormat",
  "Maturity date must be in YYYY-MM-DD format": "maturityDateFormat",
  "Current balance must be 0 or greater": "currentBalanceMin",
  "Current balance cannot exceed 10,000,000 RON": "currentBalanceMax",
  "Earned interest must be 0 or greater": "earnedInterestMin",
  "Earned interest cannot exceed 10,000,000 RON": "earnedInterestMax",
  "Maturity date must be after start date": "maturityAfterStart",
  "Current balance should not be less than principal amount":
    "balanceBelowPrincipal",
  "Transaction date is required": "transactionDateRequired",
  "Transaction date must be in YYYY-MM-DD format": "transactionDateFormat",
  "Settlement date is required": "settlementDateRequired",
  "Settlement date must be in YYYY-MM-DD format": "settlementDateFormat",
  "Type must be either BUY or SELL": "typeBuyOrSell",
  "Symbol is required": "symbolRequired",
  "Symbol must be 50 characters or less": "symbolMaxLength",
  "Quantity must be greater than 0": "quantityGreaterThanZero",
  "Unit price must be greater than 0": "unitPriceMin",
  "Unit price cannot exceed 1,000,000 RON": "unitPriceMax",
  "Gross amount must be 0 or greater": "grossAmountMin",
  "Gross amount cannot exceed 100,000,000 RON": "grossAmountMax",
  "Commission must be 0 or greater": "commissionMin",
  "Commission cannot exceed 1,000,000 RON": "commissionMax",
  "Settlement commission must be 0 or greater": "settlementCommissionMin",
  "Settlement commission cannot exceed 1,000,000 RON":
    "settlementCommissionMax",
  "Other fees must be 0 or greater": "otherFeesMin",
  "Other fees cannot exceed 1,000,000 RON": "otherFeesMax",
  "External costs must be 0 or greater": "externalCostsMin",
  "External costs cannot exceed 1,000,000 RON": "externalCostsMax",
  "Net amount cannot exceed 100,000,000 RON": "netAmountMax",
  "Realized profit cannot exceed 100,000,000 RON": "realizedProfitMax",
  "Realized profit CCY cannot exceed 100,000,000": "realizedProfitCcyMax",
  "Tax withheld must be 0 or greater": "taxWithheldMin",
  "Tax withheld cannot exceed 1,000,000 RON": "taxWithheldMax",
  "Market Identifier Code (MIC) is required": "micRequired",
  "Market Identifier Code must be 20 characters or less": "micMaxLength",
  "Realized profit is required for SELL transactions":
    "realizedProfitRequiredForSell",
  "Symbol must be 30 characters or less": "symbolMaxLengthEtf",
  "Symbol must start with a letter or digit and contain only letters, digits, dots, underscores, or hyphens":
    "symbolFormat",
  "Symbol may only contain letters, numbers, dots, underscores, or hyphens":
    "symbolFormat",
  "Label is required": "labelRequired",
  "Label must be 200 characters or less": "labelMaxLength",
  "Volume must be greater than 0": "volumeMin",
  "Volume cannot exceed 1 billion units": "volumeMax",
  "Actual price must be greater than 0": "actualPriceMin",
  "Actual price cannot exceed 1,000,000": "actualPriceMax",
  "Opening price must be greater than 0": "openingPriceMin",
  "Opening price cannot exceed 1,000,000": "openingPriceMax",
  "Currency must be EUR, USD, or RON": "currencyEurUsdRon",
  "Name is required": "nameRequired",
  "Name must be 200 characters or less": "nameMaxLength",
  "Opened date must be in YYYY-MM-DD format": "openedDateFormat",
  "Status date is required": "statusDateRequired",
  "Status date must be in YYYY-MM-DD format": "statusDateFormat",
  "Total value must be at least 0.01 RON": "totalValueMin",
  "Total value cannot exceed 100,000,000 RON": "totalValueMax",
  "Profit cannot be less than -100,000,000 RON": "profitMin",
  "Profit cannot exceed 100,000,000 RON": "profitMax",
  "Bonds percentage must be 0 or greater": "bondsPercentMin",
  "Bonds percentage cannot exceed 100%": "bondsPercentMax",
  "Invested amount cannot be negative": "investedAmountNegative",
} as const;

export type ValidationErrorCode =
  (typeof ZOD_MESSAGE_TO_CODE)[keyof typeof ZOD_MESSAGE_TO_CODE] | "validationUnknown";

const isZodMessageKey = (
  message: string,
): message is keyof typeof ZOD_MESSAGE_TO_CODE => message in ZOD_MESSAGE_TO_CODE;

export const zodMessageToCode = (message: string): ValidationErrorCode =>
  isZodMessageKey(message) ? ZOD_MESSAGE_TO_CODE[message] : "validationUnknown";
